" Name:         Lazerwave
" Description:  Port of Jared Jones' great VSCode theme 
" Author:       Jordan Sullivan <jordanmsllvn@gmail.com>
" Maintainer:   Jordan Sullivan <jordanmsllvn@gmail.com>
" License:      Public domain
" Last Updated: Sat 11 Apr 2020 07:09:19 PM MDT

" Generated by Colortemplate v2.0.0

set background=dark

hi clear
if exists('syntax_on')
  syntax reset
endif

let g:colors_name = 'lazerwave'

let s:t_Co = exists('&t_Co') && !empty(&t_Co) && &t_Co > 1 ? &t_Co : 2
let s:italics = (&t_ZH != '' && &t_ZH != '[7m') || has('gui_running')

hi! link QuickFixLine Search
hi! link StatusLineTerm StatusLine
hi! link StatusLineTermNC StatusLineNC
hi! link Boolean Constant
hi! link Character Constant
hi! link Conditional Statement
hi! link Define PreProc
hi! link Debug Special
hi! link Delimiter Special
hi! link Exception Statement
hi! link Float Constant
hi! link Include PreProc
hi! link Keyword Statement
hi! link Label Statement
hi! link Macro PreProc
hi! link PreCondit PreProc
hi! link Repeat Statement
hi! link SpecialChar Special
hi! link SpecialComment Special
hi! link StorageClass Type
hi! link Structure Type
hi! link Typedef Type
hi! link Function Identifier
hi! link lCursor Cursor

if (has('termguicolors') && &termguicolors) || has('gui_running')
  let g:terminal_ansi_colors = ['#27212e', '#eb64b9', '#74dfc4', '#ffe261',
        \ '#40b4c4', '#b381c5', '#b4dce7', '#f8f2ff', '#d2d2d2', '#ff6400',
        \ '#64ff00', '#ffff64', '#0064ff', '#ff64ff', '#64ffff', '#ffffff']
  if get(g:, 'lazerwave_transp_bg', 0) && !has('gui_running')
    hi Normal guifg=#f8f2ff guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi Terminal guifg=#f8f2ff guibg=NONE guisp=NONE gui=NONE cterm=NONE
  else
    hi Normal guifg=#f8f2ff guibg=#27212e guisp=NONE gui=NONE cterm=NONE
    hi Terminal guifg=#f8f2ff guibg=#221c29 guisp=NONE gui=NONE cterm=NONE
  endif
  hi ColorColumn guifg=fg guibg=#27212e guisp=NONE gui=NONE cterm=NONE
  hi Conceal guifg=NONE guibg=NONE guisp=NONE gui=NONE ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Cursor guifg=NONE guibg=NONE guisp=NONE gui=NONE ctermfg=NONE ctermbg=NONE cterm=NONE
  hi CursorColumn guifg=#f8f2ff guibg=#27212e guisp=NONE gui=NONE cterm=NONE
  hi CursorLine guifg=NONE guibg=#221c29 guisp=NONE gui=NONE cterm=NONE
  hi CursorLineNr guifg=#74dfc4 guibg=#27212e guisp=NONE gui=NONE cterm=NONE
  hi DiffAdd guifg=#40b4c4 guibg=#27212e guisp=NONE gui=reverse cterm=reverse
  hi DiffChange guifg=#eb64b9 guibg=#27212e guisp=NONE gui=reverse cterm=reverse
  hi DiffDelete guifg=#eb6668 guibg=#27212e guisp=NONE gui=reverse cterm=reverse
  hi DiffText guifg=#f8f2ff guibg=#27212e guisp=NONE gui=bold,reverse cterm=bold,reverse
  hi Directory guifg=#f8f2ff guibg=#27212e guisp=NONE gui=NONE cterm=NONE
  hi EndOfBuffer guifg=#1a1421 guibg=#27212e guisp=NONE gui=NONE cterm=NONE
  hi ErrorMsg guifg=#eb6668 guibg=#27212e guisp=NONE gui=reverse cterm=reverse
  hi FoldColumn guifg=#f8f2ff guibg=#27212e guisp=NONE gui=NONE cterm=NONE
  hi Folded guifg=#f8f2ff guibg=#1a1421 guisp=NONE gui=italic cterm=italic
  hi IncSearch guifg=#f8f2ff guibg=#1a1421 guisp=NONE gui=standout cterm=standout
  hi LineNr guifg=#46404d guibg=#27212e guisp=NONE gui=NONE cterm=NONE
  hi MatchParen guifg=#ffe261 guibg=#27212e guisp=NONE gui=NONE cterm=NONE
  hi ModeMsg guifg=#f8f2ff guibg=#27212e guisp=NONE gui=NONE cterm=NONE
  hi MoreMsg guifg=#f8f2ff guibg=#27212e guisp=NONE gui=NONE cterm=NONE
  hi NonText guifg=#eb64b9 guibg=#27212e guisp=NONE gui=NONE cterm=NONE
  hi Pmenu guifg=#f8f2ff guibg=#221c29 guisp=NONE gui=NONE cterm=NONE
  hi PmenuSbar guifg=#f8f2ff guibg=#27212e guisp=NONE gui=NONE cterm=NONE
  hi PmenuSel guifg=#74dfc4 guibg=#1a1421 guisp=NONE gui=NONE cterm=NONE
  hi PmenuThumb guifg=#f8f2ff guibg=#27212e guisp=NONE gui=NONE cterm=NONE
  hi Question guifg=#f8f2ff guibg=#27212e guisp=NONE gui=NONE cterm=NONE
  hi Search guifg=#f8f2ff guibg=#1a1421 guisp=NONE gui=NONE cterm=NONE
  hi SignColumn guifg=#f8f2ff guibg=#221c29 guisp=NONE gui=NONE cterm=NONE
  hi SpecialKey guifg=#f8f2ff guibg=#27212e guisp=NONE gui=NONE cterm=NONE
  hi SpellBad guifg=#f8f2ff guibg=#27212e guisp=#eb64b9 gui=NONE cterm=NONE
  hi SpellCap guifg=#f8f2ff guibg=#27212e guisp=#40b4c4 gui=NONE cterm=NONE
  hi SpellLocal guifg=#f8f2ff guibg=#27212e guisp=#b381c5 gui=NONE cterm=NONE
  hi SpellRare guifg=#f8f2ff guibg=#27212e guisp=#b4dce7 gui=reverse cterm=reverse
  hi StatusLine guifg=#f8f2ff guibg=#27212e guisp=NONE gui=NONE cterm=NONE
  hi StatusLineNC guifg=#f8f2ff guibg=#27212e guisp=NONE gui=NONE cterm=NONE
  hi TabLine guifg=#f8f2ff guibg=#27212e guisp=NONE gui=NONE cterm=NONE
  hi TabLineFill guifg=#f8f2ff guibg=#27212e guisp=NONE gui=NONE cterm=NONE
  hi TabLineSel guifg=#f8f2ff guibg=#27212e guisp=NONE gui=NONE cterm=NONE
  hi Title guifg=#eb64b9 guibg=#27212e guisp=NONE gui=NONE cterm=NONE
  hi VertSplit guifg=#1a1421 guibg=#27212e guisp=NONE gui=NONE cterm=NONE
  hi Visual guifg=#1a1421 guibg=#40b4c4 guisp=NONE gui=NONE cterm=NONE
  hi VisualNOS guifg=#74dfc4 guibg=#27212e guisp=NONE gui=NONE cterm=NONE
  hi WarningMsg guifg=#ffe261 guibg=#27212e guisp=NONE gui=NONE cterm=NONE
  hi WildMenu guifg=#f8f2ff guibg=#27212e guisp=NONE gui=NONE cterm=NONE
  hi Comment guifg=#91889b guibg=NONE guisp=NONE gui=italic cterm=italic
  hi Constant guifg=#ffe261 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Error guifg=#eb6668 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi Identifier guifg=#eb64b9 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Ignore guifg=#f8f2ff guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi PreProc guifg=#f8f2ff guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Special guifg=#91889b guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Statement guifg=#40b4c4 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Todo guifg=#74dfc4 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Type guifg=#74dfc4 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Underlined guifg=#f8f2ff guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi String guifg=#b4dce7 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Operator guifg=#74dfc4 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Number guifg=#b381c5 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi CursorIM guifg=NONE guibg=fg guisp=NONE gui=NONE cterm=NONE
  hi ToolbarLine guifg=NONE guibg=#27212e guisp=NONE gui=NONE cterm=NONE
  hi ToolbarButton guifg=#f8f2ff guibg=#27212e guisp=NONE gui=bold cterm=bold
  hi Tag guifg=#74dfc4 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link CocErrorSign Error
  hi CocHighlightText guifg=#f8f2ff guibg=#1a1421 guisp=NONE gui=bold cterm=bold
  hi jsArrow guifg=#74dfc4 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi jsThis guifg=#ffe261 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi jsIdentifierProp guifg=#40b4c4 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi jsVariableType guifg=#40b4c4 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi jsObject guifg=#74dfc4 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi jsSuper guifg=#74dfc4 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi jsxTagName guifg=#74dfc4 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi jsIf guifg=#40b4c4 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi jsElse guifg=#40b4c4 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi jsTry guifg=#40b4c4 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi jsCatch guifg=#40b4c4 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi jsObjectKey guifg=#eb64b9 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link jsObjectKeyString jsObjectKey
  hi GitGutterAdd guifg=#40b4c4 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi GitGutterChange guifg=#ffe261 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi GitGutterDelete guifg=#eb6668 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link phpStorageClass phpStructure
  hi! link phpStringSingle phpStringDouble
  hi phpIdentifier guifg=#f8f2ff guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi phpStructure guifg=#40b4c4 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi phpStringDouble guifg=#b381c5 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi phpNumber guifg=#40b4c4 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link phpConditional phpStructure
  hi! link phpRepeat phpStructure
  hi phpOperator guifg=#716385 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi phpVarSelector guifg=#eb64b9 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi phpMethodsVar guifg=#40b4c4 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi markdownHeadingDelimiter guifg=#eb64b9 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi markdownH1 guifg=#40b4c4 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi markdownH2 guifg=#40b4c4 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi markdownH3 guifg=#40b4c4 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi markdownH5 guifg=#40b4c4 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi markdownH5 guifg=#40b4c4 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi markdownH6 guifg=#40b4c4 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi markdownCode guifg=#eb64b9 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi markdownCodeDelimiter guifg=#74dfc4 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi markdownListMarker guifg=#74dfc4 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi markdownLink guifg=#74dfc4 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi markdownLinkText guifg=#ffe261 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi markdownUrl guifg=#74dfc4 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  if !s:italics
    hi Folded gui=NONE cterm=NONE
    hi Comment gui=NONE cterm=NONE
  endif
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 256
  if get(g:, 'lazerwave_transp_bg', 0)
    hi Normal ctermfg=255 ctermbg=NONE cterm=NONE
    hi Terminal ctermfg=255 ctermbg=NONE cterm=NONE
  else
    hi Normal ctermfg=255 ctermbg=235 cterm=NONE
    if !has('patch-8.0.0616') " Fix for Vim bug
      set background=dark
    endif
    hi Terminal ctermfg=255 ctermbg=234 cterm=NONE
  endif
  hi ColorColumn ctermfg=fg ctermbg=235 cterm=NONE
  hi Conceal ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Cursor ctermfg=NONE ctermbg=NONE cterm=NONE
  hi CursorColumn ctermfg=255 ctermbg=235 cterm=NONE
  hi CursorLine ctermfg=NONE ctermbg=234 cterm=NONE
  hi CursorLineNr ctermfg=79 ctermbg=235 cterm=NONE
  hi DiffAdd ctermfg=73 ctermbg=235 cterm=reverse
  hi DiffChange ctermfg=169 ctermbg=235 cterm=reverse
  hi DiffDelete ctermfg=203 ctermbg=235 cterm=reverse
  hi DiffText ctermfg=255 ctermbg=235 cterm=bold,reverse
  hi Directory ctermfg=255 ctermbg=235 cterm=NONE
  hi EndOfBuffer ctermfg=233 ctermbg=235 cterm=NONE
  hi ErrorMsg ctermfg=203 ctermbg=235 cterm=reverse
  hi FoldColumn ctermfg=255 ctermbg=235 cterm=NONE
  hi Folded ctermfg=255 ctermbg=233 cterm=italic
  hi IncSearch ctermfg=255 ctermbg=233 cterm=reverse
  hi LineNr ctermfg=238 ctermbg=235 cterm=NONE
  hi MatchParen ctermfg=221 ctermbg=235 cterm=NONE
  hi ModeMsg ctermfg=255 ctermbg=235 cterm=NONE
  hi MoreMsg ctermfg=255 ctermbg=235 cterm=NONE
  hi NonText ctermfg=169 ctermbg=235 cterm=NONE
  hi Pmenu ctermfg=255 ctermbg=234 cterm=NONE
  hi PmenuSbar ctermfg=255 ctermbg=235 cterm=NONE
  hi PmenuSel ctermfg=79 ctermbg=233 cterm=NONE
  hi PmenuThumb ctermfg=255 ctermbg=235 cterm=NONE
  hi Question ctermfg=255 ctermbg=235 cterm=NONE
  hi Search ctermfg=255 ctermbg=233 cterm=NONE
  hi SignColumn ctermfg=255 ctermbg=234 cterm=NONE
  hi SpecialKey ctermfg=255 ctermbg=235 cterm=NONE
  hi SpellBad ctermfg=255 ctermbg=235 cterm=NONE
  hi SpellCap ctermfg=255 ctermbg=235 cterm=NONE
  hi SpellLocal ctermfg=255 ctermbg=235 cterm=NONE
  hi SpellRare ctermfg=255 ctermbg=235 cterm=reverse
  hi StatusLine ctermfg=255 ctermbg=235 cterm=NONE
  hi StatusLineNC ctermfg=255 ctermbg=235 cterm=NONE
  hi TabLine ctermfg=255 ctermbg=235 cterm=NONE
  hi TabLineFill ctermfg=255 ctermbg=235 cterm=NONE
  hi TabLineSel ctermfg=255 ctermbg=235 cterm=NONE
  hi Title ctermfg=169 ctermbg=235 cterm=NONE
  hi VertSplit ctermfg=233 ctermbg=235 cterm=NONE
  hi Visual ctermfg=233 ctermbg=73 cterm=NONE
  hi VisualNOS ctermfg=79 ctermbg=235 cterm=NONE
  hi WarningMsg ctermfg=221 ctermbg=235 cterm=NONE
  hi WildMenu ctermfg=255 ctermbg=235 cterm=NONE
  hi Comment ctermfg=103 ctermbg=NONE cterm=italic
  hi Constant ctermfg=221 ctermbg=NONE cterm=NONE
  hi Error ctermfg=203 ctermbg=NONE cterm=bold
  hi Identifier ctermfg=169 ctermbg=NONE cterm=NONE
  hi Ignore ctermfg=255 ctermbg=NONE cterm=NONE
  hi PreProc ctermfg=255 ctermbg=NONE cterm=NONE
  hi Special ctermfg=103 ctermbg=NONE cterm=NONE
  hi Statement ctermfg=73 ctermbg=NONE cterm=NONE
  hi Todo ctermfg=79 ctermbg=NONE cterm=NONE
  hi Type ctermfg=79 ctermbg=NONE cterm=NONE
  hi Underlined ctermfg=255 ctermbg=NONE cterm=NONE
  hi String ctermfg=152 ctermbg=NONE cterm=NONE
  hi Operator ctermfg=79 ctermbg=NONE cterm=NONE
  hi Number ctermfg=140 ctermbg=NONE cterm=NONE
  hi CursorIM ctermfg=NONE ctermbg=fg cterm=NONE
  hi ToolbarLine ctermfg=NONE ctermbg=235 cterm=NONE
  hi ToolbarButton ctermfg=255 ctermbg=235 cterm=bold
  hi Tag ctermfg=79 ctermbg=NONE cterm=NONE
  hi! link CocErrorSign Error
  hi CocHighlightText ctermfg=255 ctermbg=233 cterm=bold
  hi jsArrow ctermfg=79 ctermbg=NONE cterm=NONE
  hi jsThis ctermfg=221 ctermbg=NONE cterm=bold
  hi jsIdentifierProp ctermfg=73 ctermbg=NONE cterm=NONE
  hi jsVariableType ctermfg=73 ctermbg=NONE cterm=NONE
  hi jsObject ctermfg=79 ctermbg=NONE cterm=NONE
  hi jsSuper ctermfg=79 ctermbg=NONE cterm=bold
  hi jsxTagName ctermfg=79 ctermbg=NONE cterm=NONE
  hi jsIf ctermfg=73 ctermbg=NONE cterm=bold
  hi jsElse ctermfg=73 ctermbg=NONE cterm=bold
  hi jsTry ctermfg=73 ctermbg=NONE cterm=bold
  hi jsCatch ctermfg=73 ctermbg=NONE cterm=bold
  hi jsObjectKey ctermfg=169 ctermbg=NONE cterm=NONE
  hi! link jsObjectKeyString jsObjectKey
  hi GitGutterAdd ctermfg=73 ctermbg=NONE cterm=NONE
  hi GitGutterChange ctermfg=221 ctermbg=NONE cterm=NONE
  hi GitGutterDelete ctermfg=203 ctermbg=NONE cterm=NONE
  hi! link phpStorageClass phpStructure
  hi! link phpStringSingle phpStringDouble
  hi phpIdentifier ctermfg=255 ctermbg=NONE cterm=NONE
  hi phpStructure ctermfg=73 ctermbg=NONE cterm=bold
  hi phpStringDouble ctermfg=140 ctermbg=NONE cterm=NONE
  hi phpNumber ctermfg=73 ctermbg=NONE cterm=NONE
  hi! link phpConditional phpStructure
  hi! link phpRepeat phpStructure
  hi phpOperator ctermfg=60 ctermbg=NONE cterm=bold
  hi phpVarSelector ctermfg=169 ctermbg=NONE cterm=bold
  hi phpMethodsVar ctermfg=73 ctermbg=NONE cterm=NONE
  hi markdownHeadingDelimiter ctermfg=169 ctermbg=NONE cterm=NONE
  hi markdownH1 ctermfg=73 ctermbg=NONE cterm=NONE
  hi markdownH2 ctermfg=73 ctermbg=NONE cterm=NONE
  hi markdownH3 ctermfg=73 ctermbg=NONE cterm=NONE
  hi markdownH5 ctermfg=73 ctermbg=NONE cterm=NONE
  hi markdownH5 ctermfg=73 ctermbg=NONE cterm=NONE
  hi markdownH6 ctermfg=73 ctermbg=NONE cterm=NONE
  hi markdownCode ctermfg=169 ctermbg=NONE cterm=NONE
  hi markdownCodeDelimiter ctermfg=79 ctermbg=NONE cterm=NONE
  hi markdownListMarker ctermfg=79 ctermbg=NONE cterm=NONE
  hi markdownLink ctermfg=79 ctermbg=NONE cterm=NONE
  hi markdownLinkText ctermfg=221 ctermbg=NONE cterm=NONE
  hi markdownUrl ctermfg=79 ctermbg=NONE cterm=NONE
  if !s:italics
    hi Folded cterm=NONE
    hi Comment cterm=NONE
  endif
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 8
  if get(g:, 'lazerwave_transp_bg', 0)
    hi Normal ctermfg=White ctermbg=NONE cterm=NONE
    hi Terminal ctermfg=White ctermbg=NONE cterm=NONE
  else
    hi Normal ctermfg=White ctermbg=Black cterm=NONE
    hi Terminal ctermfg=White ctermbg=Black cterm=NONE
  endif
  hi ColorColumn ctermfg=fg ctermbg=Black cterm=NONE
  hi Conceal ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Cursor ctermfg=NONE ctermbg=NONE cterm=NONE
  hi CursorColumn ctermfg=White ctermbg=Black cterm=NONE
  hi CursorLine ctermfg=NONE ctermbg=Black cterm=NONE
  hi CursorLineNr ctermfg=White ctermbg=Black cterm=NONE
  hi DiffAdd ctermfg=White ctermbg=Black cterm=reverse
  hi DiffChange ctermfg=White ctermbg=Black cterm=reverse
  hi DiffDelete ctermfg=Red ctermbg=Black cterm=reverse
  hi DiffText ctermfg=White ctermbg=Black cterm=bold,reverse
  hi Directory ctermfg=White ctermbg=Black cterm=NONE
  hi EndOfBuffer ctermfg=Black ctermbg=Black cterm=NONE
  hi ErrorMsg ctermfg=Red ctermbg=Black cterm=reverse
  hi FoldColumn ctermfg=White ctermbg=Black cterm=NONE
  hi Folded ctermfg=White ctermbg=Black cterm=italic
  hi IncSearch ctermfg=White ctermbg=Black cterm=reverse
  hi LineNr ctermfg=White ctermbg=Black cterm=NONE
  hi MatchParen ctermfg=White ctermbg=Black cterm=NONE
  hi ModeMsg ctermfg=White ctermbg=Black cterm=NONE
  hi MoreMsg ctermfg=White ctermbg=Black cterm=NONE
  hi NonText ctermfg=White ctermbg=Black cterm=NONE
  hi Pmenu ctermfg=White ctermbg=Black cterm=NONE
  hi PmenuSbar ctermfg=White ctermbg=Black cterm=NONE
  hi PmenuSel ctermfg=White ctermbg=Black cterm=NONE
  hi PmenuThumb ctermfg=White ctermbg=Black cterm=NONE
  hi Question ctermfg=White ctermbg=Black cterm=NONE
  hi Search ctermfg=White ctermbg=Black cterm=NONE
  hi SignColumn ctermfg=White ctermbg=Black cterm=NONE
  hi SpecialKey ctermfg=White ctermbg=Black cterm=NONE
  hi SpellBad ctermfg=White ctermbg=Black cterm=NONE
  hi SpellCap ctermfg=White ctermbg=Black cterm=NONE
  hi SpellLocal ctermfg=White ctermbg=Black cterm=NONE
  hi SpellRare ctermfg=White ctermbg=Black cterm=reverse
  hi StatusLine ctermfg=White ctermbg=Black cterm=NONE
  hi StatusLineNC ctermfg=White ctermbg=Black cterm=NONE
  hi TabLine ctermfg=White ctermbg=Black cterm=NONE
  hi TabLineFill ctermfg=White ctermbg=Black cterm=NONE
  hi TabLineSel ctermfg=White ctermbg=Black cterm=NONE
  hi Title ctermfg=White ctermbg=Black cterm=NONE
  hi VertSplit ctermfg=Black ctermbg=Black cterm=NONE
  hi Visual ctermfg=Black ctermbg=White cterm=NONE
  hi VisualNOS ctermfg=White ctermbg=Black cterm=NONE
  hi WarningMsg ctermfg=White ctermbg=Black cterm=NONE
  hi WildMenu ctermfg=White ctermbg=Black cterm=NONE
  hi Comment ctermfg=White ctermbg=NONE cterm=italic
  hi Constant ctermfg=White ctermbg=NONE cterm=NONE
  hi Error ctermfg=Red ctermbg=NONE cterm=bold
  hi Identifier ctermfg=White ctermbg=NONE cterm=NONE
  hi Ignore ctermfg=White ctermbg=NONE cterm=NONE
  hi PreProc ctermfg=White ctermbg=NONE cterm=NONE
  hi Special ctermfg=White ctermbg=NONE cterm=NONE
  hi Statement ctermfg=White ctermbg=NONE cterm=NONE
  hi Todo ctermfg=White ctermbg=NONE cterm=NONE
  hi Type ctermfg=White ctermbg=NONE cterm=NONE
  hi Underlined ctermfg=White ctermbg=NONE cterm=NONE
  hi String ctermfg=White ctermbg=NONE cterm=NONE
  hi Operator ctermfg=White ctermbg=NONE cterm=NONE
  hi Number ctermfg=White ctermbg=NONE cterm=NONE
  hi CursorIM ctermfg=NONE ctermbg=fg cterm=NONE
  hi ToolbarLine ctermfg=NONE ctermbg=Black cterm=NONE
  hi ToolbarButton ctermfg=White ctermbg=Black cterm=bold
  hi Tag ctermfg=White ctermbg=NONE cterm=NONE
  hi! link CocErrorSign Error
  hi CocHighlightText ctermfg=White ctermbg=Black cterm=bold
  hi jsArrow ctermfg=White ctermbg=NONE cterm=NONE
  hi jsThis ctermfg=White ctermbg=NONE cterm=bold
  hi jsIdentifierProp ctermfg=White ctermbg=NONE cterm=NONE
  hi jsVariableType ctermfg=White ctermbg=NONE cterm=NONE
  hi jsObject ctermfg=White ctermbg=NONE cterm=NONE
  hi jsSuper ctermfg=White ctermbg=NONE cterm=bold
  hi jsxTagName ctermfg=White ctermbg=NONE cterm=NONE
  hi jsIf ctermfg=White ctermbg=NONE cterm=bold
  hi jsElse ctermfg=White ctermbg=NONE cterm=bold
  hi jsTry ctermfg=White ctermbg=NONE cterm=bold
  hi jsCatch ctermfg=White ctermbg=NONE cterm=bold
  hi jsObjectKey ctermfg=White ctermbg=NONE cterm=NONE
  hi! link jsObjectKeyString jsObjectKey
  hi GitGutterAdd ctermfg=White ctermbg=NONE cterm=NONE
  hi GitGutterChange ctermfg=White ctermbg=NONE cterm=NONE
  hi GitGutterDelete ctermfg=Red ctermbg=NONE cterm=NONE
  hi! link phpStorageClass phpStructure
  hi! link phpStringSingle phpStringDouble
  hi phpIdentifier ctermfg=White ctermbg=NONE cterm=NONE
  hi phpStructure ctermfg=White ctermbg=NONE cterm=bold
  hi phpStringDouble ctermfg=White ctermbg=NONE cterm=NONE
  hi phpNumber ctermfg=White ctermbg=NONE cterm=NONE
  hi! link phpConditional phpStructure
  hi! link phpRepeat phpStructure
  hi phpOperator ctermfg=White ctermbg=NONE cterm=bold
  hi phpVarSelector ctermfg=White ctermbg=NONE cterm=bold
  hi phpMethodsVar ctermfg=White ctermbg=NONE cterm=NONE
  hi markdownHeadingDelimiter ctermfg=White ctermbg=NONE cterm=NONE
  hi markdownH1 ctermfg=White ctermbg=NONE cterm=NONE
  hi markdownH2 ctermfg=White ctermbg=NONE cterm=NONE
  hi markdownH3 ctermfg=White ctermbg=NONE cterm=NONE
  hi markdownH5 ctermfg=White ctermbg=NONE cterm=NONE
  hi markdownH5 ctermfg=White ctermbg=NONE cterm=NONE
  hi markdownH6 ctermfg=White ctermbg=NONE cterm=NONE
  hi markdownCode ctermfg=White ctermbg=NONE cterm=NONE
  hi markdownCodeDelimiter ctermfg=White ctermbg=NONE cterm=NONE
  hi markdownListMarker ctermfg=White ctermbg=NONE cterm=NONE
  hi markdownLink ctermfg=White ctermbg=NONE cterm=NONE
  hi markdownLinkText ctermfg=White ctermbg=NONE cterm=NONE
  hi markdownUrl ctermfg=White ctermbg=NONE cterm=NONE
  if !s:italics
    hi Folded cterm=NONE
    hi Comment cterm=NONE
  endif
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 2
  hi Normal term=NONE
  hi ColorColumn term=reverse
  hi Conceal term=NONE
  hi Cursor term=NONE
  hi CursorColumn term=reverse
  hi CursorLine term=underline
  hi CursorLineNr term=bold,italic,reverse,underline
  hi DiffAdd term=reverse,underline
  hi DiffChange term=reverse,underline
  hi DiffDelete term=reverse,underline
  hi DiffText term=bold,reverse,underline
  hi Directory term=NONE
  hi EndOfBuffer term=NONE
  hi ErrorMsg term=bold,italic,reverse
  hi FoldColumn term=reverse
  hi Folded term=italic,reverse,underline
  hi IncSearch term=bold,italic,reverse
  hi LineNr term=reverse
  hi MatchParen term=bold,underline
  hi ModeMsg term=NONE
  hi MoreMsg term=NONE
  hi NonText term=NONE
  hi Pmenu term=reverse
  hi PmenuSbar term=NONE
  hi PmenuSel term=NONE
  hi PmenuThumb term=NONE
  hi Question term=standout
  hi Search term=italic,underline
  hi SignColumn term=reverse
  hi SpecialKey term=bold
  hi SpellBad term=italic,underline
  hi SpellCap term=italic,underline
  hi SpellLocal term=italic,underline
  hi SpellRare term=italic,underline
  hi StatusLine term=bold,reverse
  hi StatusLineNC term=reverse
  hi TabLine term=italic,reverse,underline
  hi TabLineFill term=reverse,underline
  hi TabLineSel term=bold
  hi Title term=bold
  hi VertSplit term=reverse
  hi Visual term=reverse
  hi VisualNOS term=NONE
  hi WarningMsg term=standout
  hi WildMenu term=bold
  hi Comment term=italic
  hi Constant term=bold,italic
  hi Error term=reverse
  hi Identifier term=italic
  hi Ignore term=NONE
  hi PreProc term=italic
  hi Special term=bold,italic
  hi Statement term=bold
  hi Todo term=bold,underline
  hi Type term=bold
  hi Underlined term=underline
  hi CursorIM term=NONE
  hi ToolbarLine term=reverse
  hi ToolbarButton term=bold,reverse
  if !s:italics
    hi CursorLineNr term=bold,reverse,underline
    hi ErrorMsg term=bold,reverse
    hi Folded term=reverse,underline
    hi IncSearch term=bold,reverse
    hi Search term=underline
    hi SpellBad term=underline
    hi SpellCap term=underline
    hi SpellLocal term=underline
    hi SpellRare term=underline
    hi TabLine term=reverse,underline
    hi Comment term=NONE
    hi Constant term=bold
    hi Identifier term=NONE
    hi PreProc term=NONE
    hi Special term=bold
  endif
  unlet s:t_Co s:italics
  finish
endif

" Background: dark
" Color: maxblue       #40b4c4                 ~           White
" Color: hotpink       #eb64b9                 ~           White
" Color: red           #eb6668                 ~           Red
" Color: powderblue    #b4dce7                 ~           White
" Color: afviolet      #b381c5                 ~           White
" Color: pearlaq       #74dfc4                 ~           White
" Color: oldlaven      #91889b                 ~           White
" Color: romsilv       #716385                 ~           White
" Color: mustard       #ffe261                 ~           White
" Color: white         #f8f2ff                 ~           White
" Color: black         #27212e                 ~           Black
" Color: darker        #221c29                 ~           Black
" Color: lighter       #46404d                 ~           White
" Color: blacker       #1a1421                 ~           Black
" Color: brightblack   rgb(210, 210, 210)        ~         DarkGrey
" Color: brightred     rgb(255, 100,   0)        ~         LightRed
" Color: brightgreen   rgb(100, 255,   0)        ~         LightGreen
" Color: brightyellow  rgb(255, 255, 100)        ~         LightYellow
" Color: brightblue    rgb(  0, 100, 255)        ~         LightBlue
" Color: brightmagenta rgb(255, 100, 255)        ~         LightMagenta
" Color: brightcyan    rgb(100, 255, 255)        ~         LightCyan
" Color: brightwhite   rgb(255, 255, 255)        ~         LightCyan
" Term colors: black hotpink pearlaq mustard maxblue afviolet powderblue white
" Term colors: brightblack brightred brightgreen brightyellow
" Term colors: brightblue brightmagenta brightcyan brightwhite
" vim: et ts=2 sw=2
